title: Pranav Shankar Girish
logo: /images/headshot.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p align="center">
    Master of Business Analytics, MIT
    <br>
    B.Tech, IIT Delhi
    <br><br>
    <img src="images/linkedin_logo-2.png?raw=true" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/pranav-shankar-girish/">pranavshankargirish</a> 
    <br>
    <img src="images/github_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://github.com/PranavShankarGirish/">pranavshankargirish</a> 
    <br>
    <br>
    <img src="images/iitd_logo-2.png?raw=true" width="30%" height="30%"/>
    <img src="images/mit_logo-2.png?raw=true" width="30%" height="30%"/>
  </p>
show_downloads: false
theme: jekyll-theme-minimal
